### ISSUE TITLE
Octant throwing plugin error and no contexts showing in UI since upgrade

### ISSUE THREAD

**Issue by asanami** [vmware-tanzu/octant#1173]
Since upgrading and starting up octant, it nows throws the following ERROR and not showing any context in the UI.

```
2020-07-28T13:48:28.125+0100	ERROR	plugin/manager.go:342	unable to add %s to JavaScript plugin watcher
github.com/vmware-tanzu/octant/pkg/plugin.(*Manager).watchJS
	/private/tmp/octant-20200721-47339-lwdwoh/src/github.com/vmware-tanzu/octant/pkg/plugin/manager.go:342
2020-07-28T13:48:28.125+0100	INFO	plugin/manager.go:346	watching for new JavaScript plugins in ["/Users/asanami/.config/octant/plugins"]
2020-07-28T13:48:28.682+0100	INFO	dash/dash.go:573	using api service
```

**Environment:**

- Octant version (use `octant version`): 
Version:  0.14.1

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

OX 10.14.6

**Comment by wwitzel3** [comment]
I created a PR #1174 that will fix that logger output so that it contains the path the Octant failed to watch. The failing to watch any folder for new plugins should not impact loading the Octant UI itself.

Are there any errors in the browser console?

If you run Octant with `-vv` to get the verbose logging output, we can probably find out better what is happening.

**Comment by wwitzel3** [comment]
That could probably be changed to a warning instead of an error.

**Comment by wwitzel3** [comment]
I'm going to close this now. Feel free to re-open it if I missed something.

I updated the logger to use a Warning instead of an Error and I also made sure the path was properly used in the string formatting so the output is actually useful.

Let me know if you were encountering any problems using Octant as a result of this error or if it was just the error output itself that was concerning.
