### ISSUE TITLE
Document Differences From official Kubernetes Dashboard

### ISSUE THREAD

**Issue by geekdave** [vmware-tanzu/octant#127]
Thanks for contributing this project to the community!  As a newcomer to k8s, my initial first question was: "how is this different from the official kubernetes dashboard?"  (https://github.com/kubernetes/dashboard) - Might it be possible to include a brief blurb in the README calling out the similarities/differences?

**Comment by rdelpret** [comment]
I think the kubernetes dashboard is deprecated because it uses heapster?

**Comment by bryanl** [comment]
(I'm not closing it because we should get this in a `FAQ.md`)

How does Octant differ from the Kubernetes dashboard?

* Octant does not run in your cluster (by default). It runs locally on your workstation and uses your kubeconfig files
* Octant has a resource viewer which contains a DAG that can link related objects
* Octant supports CRDs
* The dashboard functionality of Octant isn't the #1 priority. The tool was created to help give users of Kubernetes more information in an easier fashion than `kubectl [get|describe]` 
* Octant can be extended with plugins
* Octant is currently being developed
* Octant is based on newer web technologies. The Kubernetes dashboard is based on AngularJS that has been superseded by Angular.

**Comment by mikeroySoft** [comment]
Resolved as per PR #314 , details are now in docs/FAQ.md
