### ISSUE TITLE
DashboardClient#List behaves inconsistency when resource is not available in cluster

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1526]
**What steps did you take and what happened:**

Using the Knative plugin and a clean kind cluster `kind create cluster`. When viewing the overview page for the plugin, the layout flip-flops between an error page and an empty listing. The error page is rendered if any of the DashboardClient calls throw, the empty listing is returned if all calls to DashboardClient#List return an empty array.

**What did you expect to happen:**

The DashboardClient should consistently throw errors when the CRD is not installed.

**Environment:**

- Octant version (use `octant version`): 0.16.1
- Kubernetes version (use `kubectl version`): 1.19.1
- Knative Plugin: [v0.2.0](https://github.com/vmware-tanzu/octant-plugin-for-knative/releases/tag/v0.2.0)

**Comment by wwitzel3** [comment]
Originally I was going to try to put this in to 0.16.2 but after some investigation this issue is more systemic.

In our list call we are doing an access check. This access check is actually masking the IsNoMatch error from the API, intern, we treat it like an access denied error and start the backoff process.

	if err := dc.access.HasAccess(ctx, key, "list"); err != nil {
		if meta.IsNoMatchError(err) {
			return &unstructured.UnstructuredList{}, false, err
		}
		if !dc.isBackingOff(ctx, key) {
			dc.backoff(ctx, key)
		}
		return nil, false, fmt.Errorf("check access to list %s: %w", key, err)
	}

So normally we just return an empty list if the CRD is not installed at all, this was put in place a while back, to allow Octant to 
short circuit the HasAccess checks all together for requests that weren't even installed.

The problem is, this short circuit should exist in the HasAccess method itself, not in the List/Get/Watch calls. So if this was working as it was originally intended, you'd only get the empty list as return values.

This is fine behavior for core Octant, since it will never attempt to query for a CRD that isn't part of the list of CRDs Octant fetches at startup. That behavior is not really great for a plugin, especially if you want to explicitly look for that IsNoMatch error and offer to install the CRDs from the Error Page.

**Comment by wwitzel3** [comment]
The proper way to fix this is fix how the Octant client current works. We are trying to do too much and should just be returning errors up the stack and dealing with them accordingly in the describers for our modules.
