### ISSUE TITLE
Add support for StorageClasses

### ISSUE THREAD

**Issue by alexbrand** [vmware-tanzu/octant#1794]
**Describe the problem/challenge you have**
Currently, Octant does not display storage classes under the Cluster -> Storage section.

![image](https://user-images.githubusercontent.com/545723/103907511-5a65b780-50cf-11eb-848f-be2e819d3b25.png)

**Describe the solution you'd like**
Add support for the StorageClass resource.

**Environment:**

- Octant version (use `octant version`): 
```
Version:  0.16.1
Git commit:  8aebb34922f83894fb02ad393740e96ee1b3d8fe
Built:  2020-10-08T02:48:58Z
```

Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by GuessWhoSamFoo** [comment]
We should a tracking issue for all types Octant wants to support (maybe a checklist off kubectl api-resources) and add it to the roadmap/projects. Work on these types of issues are generally left open to the community unless specifically requested since the remaining ones are less common and there are higher priority issues.
