### ISSUE TITLE
Design review issues for 0.17

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#1897]
Here is a list of issues from today's design review meeting: 

- [ ] ~~Bring the Octant icon and title back~~ moved to #1898,
- [x] Preferences: add navigation options,
- [x] `Show more` button improve design (@ibagha to provide design),
- [x] Navigation items have inconsistent height,
- [x] Align navigation with breadcrumbs and page title,
- [x] Donut chart single item remove the spacer,
- [x] Check contrast for the light theme,
- [x] Fix header issues after browse button were added (the breakpoint should go down from ~1400px)

**Comment by ibagha** [comment]
Here are some options for the button in the navbar dropdown:

![Frame 3](https://user-images.githubusercontent.com/54036938/106310232-153d2d00-6218-11eb-880b-3d7a4200d5db.jpg)

![Frame 4](https://user-images.githubusercontent.com/54036938/106310235-1706f080-6218-11eb-9d56-fcfd1e8ca76e.jpg)

I prefer the first option ([with the Clarity flat button](https://clarity.design/core-components/button/)) since the other one looks out of place. Here are some specs in the mock:
**Padding**: 10px top and bottom
**Text size**: 10px in the mock, but try to match it to the text size of of the items in the dropdown
**Line thickness for divider**: 1px
**Color of divider and font**: Same color as font that's in the dropdown, which by default should be the link color in Clarity
Hover state: Same as hover state for other dropdowns in Octant UI, light and dark

**Comment by mklanjsek** [comment]
Thank you, Isha.  Are you sure about font size, looks quite big on your mockups?

I like Frame4 better!
________________________________

**Comment by ibagha** [comment]
@mklanjsek What's the font size of the menu items in the dropdown?

**Comment by ibagha** [comment]
@mklanjsek Edits we discussed for the Electron header:
- [ ] Logo and name right now are aligned with the secondary nav; they should be aligned to the farthest left, alongside the nav primary bar 
- [ ] Chevrons should be aligned with the content panel (breadcrumbs menu, titles…), right now they are indented
- [ ] Reduce chevron size (try reducing by 8px, i.e. if they're 24x24 try 16x16)
- [ ] Reduce space between chevrons by 8px
- [ ] Reduce width of filter
- [ ] Reduce space between chevrons and filter dropdown so that they 24px apart

**Comment by wwitzel3** [comment]
I'm wondering since the name and logo now exist in the Application bar, the task/dock bar, and in the system tray, do we still need it in the header that is nested in the application? Looking at other electron applications and they don't do this.

**Comment by mklanjsek** [comment]
@ibagha and I decided to keep it like this for now and do header redesign for 0.18. That will give us enough time to consume all the feedback and fully integrate with Electron (e.g. move help items to Electron menu).

**Comment by ibagha** [comment]
@wwitzel3 It can't hurt to have the icon and name there for now as the app is being introduced, especially since it won't make a difference in terms of space. Everything in the header will span only across the 'content panel' where you see the page title, bread crumbs, tables, etc. and not the navigation bars on the side. So that space will be left empty without the logo and name instead of the header content shifting over. It's standard across apps for the header bar content to span across the content area and not the nav area, and will help in terms of association and grouping between the header items and what you're doing in the content panel.

**Comment by ibagha** [comment]
+1 to Milan. We can rethink the whole header in 0.18 when there's feedback to be incorporated
