### ISSUE TITLE
Page layout allows for buttons in-line with page title

### ISSUE THREAD

**Issue by pivotal-mikegresham** [vmware-tanzu/octant#2302]
**Describe the problem/challenge you have**
Currently, the page layout doesn't allow for a button inline with the title. Adding buttons creates a row that adds page height and is misaligned.

**Describe the solution you'd like**
We would like to have some action buttons right-aligned, inline with the title.

Example: ![Screen Shot 2021-04-12 at 10 37 21](https://user-images.githubusercontent.com/9358064/114437209-175a2b00-9b7b-11eb-9ff6-4c3887cd3f0a.png)

**Comment by wwitzel3** [comment]
I think this would involve extending the Title to support taking a ButtonGroup, similar to what we do for flex layout to allow it to have a button group associated with it. https://github.com/vmware-tanzu/octant/blob/master/pkg/view/component/flexlayout.go#L57

I don't think we want to make buttons and buttons groups a supported title component type, since I think we'd want to not have the buttons be part of the breadcrumbs for the title.

That said, it might involve needing to refactor the way we think about title components .. since right now they are a list of components that are marked as being suitable for titles.

**Comment by ftovaro** [comment]
Hi, I can work in the extension of the TitleComponent to receive a Button or ButtonGroup.

That said, I was thinking to receive an array of Buttons or a single ButtonGroup, what do you think is the best here? Or should the TitleComponent be able to receive both? What do you think?

**Comment by GuessWhoSamFoo** [comment]
It should be an arbitrary component. The distinction between a button group vs three individual button components is that a button group is for similarly grouped tasks. However, it is up to the plugin developer to choose. We're interested allowing titles to be inline with another component under a given flex layout section.

**Comment by ftovaro** [comment]
Just an update:

We asked Mike if in the issue he was talking about adding components to any title or just a page title.
The answer was that is was needed just for the title.

So, what we have to do is extend the TitleComponent to receive any other component.

Issues about this approach:

1. Styling of the tiles, organize them to be align with the component (buttons, etc)
2. How to receive the new components
3. what happens if the plugin author just inject a lot of components.

And so on.
