### ISSUE TITLE
Preserve layout in Resource Viewer

### ISSUE THREAD

**Issue by mikeroySoft** [vmware-tanzu/octant#236]
When troubleshooting services, I often times like to compare with the layouts of healthy services.

I like using the Resource View because I can drag things where I logically perceive them to be in the stack, which may be different than the initial layout.

However, once I leave that 'page', upon returning the layout is reset back to default.

It would be great if Octant would preserve the view I've created in Resource View, so I can quickly go back and forth between multiple layouts without dragging everything around each time.

**Comment by wwitzel3** [comment]
I agree this would be nice.

We will need to look into how the window size and zoom level impact this. I do worry about preserving some location and then presenting the user with a blank view because they open a new browser or resize the pane.

We could have a reset button of some kind.

Maybe we could use the ID of the resource closest to the center of the screen and load the RV back to having that focused? That might feel more odd though, since it wouldn't be exactly where you left the view.

**Comment by wwitzel3** [comment]
This was fixed by @mklanjsek

**Comment by mklanjsek** [comment]
@wwitzel3 the original request has not been implemented. If you rearrange the layout, go somewhere else and then come back to the same resource, the rearranged layout is lost.

I was thinking to implement this with a `Lock` icon in Resource Viewer - after it's clicked, we would persist the layout on client side and reuse it on sub-sequential visits to that resource.
