### ISSUE TITLE
About Version doesn't match release version

### ISSUE THREAD

**Issue by survivant** [vmware-tanzu/octant#2664]
I downloaded : octant_0.22.0_Windows-64bit  but the version is still 0.20.0

![image](https://user-images.githubusercontent.com/191879/126155878-c93fc233-687d-4f79-9850-f6d1d965aa30.png)

````
PS C:\Users\sd003526\Downloads\octant_0.22.0_Windows-64bit> octant version
Version:  0.20.0
Git commit:  b716185f5d9f85eeec5284a760d7f04dd0c03ab5
Built:  2021-05-11T17:40:32Z
PS C:\Users\sd003526\Downloads\octant_0.22.0_Windows-64bit>
````

**Comment by GuessWhoSamFoo** [comment]
I think what's happening is that the chocolatey (https://community.chocolatey.org/packages/octant) package manager has not been updated since 0.20.0

We can bump the release and it is possible to get 0.22.0 on windows from Github in the meantime via https://github.com/vmware-tanzu/octant/releases/download/v0.22.0/octant_0.22.0_Windows-64bit.zip

**Comment by survivant** [comment]
I forgot that I had octant installed by chocolatey and it's the one that is executed when I enter : octant version.

if I do .\octant.exe version I got 0.22.

not a bug.
