### ISSUE TITLE
Add keyboard shortcuts to navigate UI

### ISSUE THREAD

**Issue by alexbrand** [vmware-tanzu/octant#413]
It would be amazing to be able to move around different sections of Octant using the keyboard.

I have been noodling for a while on what the UX could be like... Two potential approaches stand out:
- [Alfred](https://www.alfredapp.com/)-style shortcut / pop-up: ctrl-k (or something else) opens up a modal with a text box. I can then type `pod`, the modal updates and shows `Overview -> Workloads -> Pods`, I hit enter and get taken to the Pods page.
- Gmail-style shortcuts: `gp` takes me to pods. `gd` takes me to deployments, etc.

Pages that display a table / list would need a way to filter and navigate using the keyboard. 

Overall, the UX could be something like this:
- `ctrl-k + pods + enter` takes me to the pod list. 
- type `nginx` filters the pod list down to nginx pods
- use arrow keys (most likely another set of keys to avoid clashing with page scrolling) to navigate to desired pod
- hit enter to open pod page

**Comment by wwitzel3** [comment]
Thanks for this suggestion, I really like this idea. If this was something you were interested in contributing, I'd be happy to review and help in anyway I can.

I think the Alfred style would be, easier initially, only because there would be less determining what the shortcuts would be, since it would just be filtering a list of destinations.

Eventually having some defined shortcuts, so, by 1.0, would be a great addition too.

I actually like the idea of having both eventually, since it makes it easier to add new locations to the popup/filter style without having to decide on shortcuts immediately.

**Comment by alexbrand** [comment]
Yeah! I think I can prototype something to see what it looks like 👍

**Comment by alexbrand** [comment]
@wwitzel3 @bryanl I put together a prototype of what I was envisioning (inspired by Alfred/Slack's quick-switcher).

Here are some GIFs that showcase the UX.

Filter down the list and hit enter to go there:
![2019-11-14 13 23 35](https://user-images.githubusercontent.com/545723/68889512-afcc5180-06e2-11ea-8aa3-05c00f6e0afa.gif)

The arrow keys can be used to go up or down in the list:
![2019-11-14 13 25 38](https://user-images.githubusercontent.com/545723/68889625-e0ac8680-06e2-11ea-82f7-c144e5fa011b.gif)

Using the mouse is also possible:
![2019-11-14 13 25 11](https://user-images.githubusercontent.com/545723/68889562-c4a8e500-06e2-11ea-9f4d-37517b25869c.gif)

Curious on your thoughts here. Happy to write up a proposal if that's the right way to go.

**Comment by wwitzel3** [comment]
@alexbrand I love this!

**Comment by alexbrand** [comment]
Yeah, I think it came out pretty cool! Should I open a PR for this? Wondering about next steps.

**Comment by wwitzel3** [comment]
Yeah I'll be happy to review it if you take the time to put up a PR. Thank you.
