### ISSUE TITLE
Dashboard still not embeddable

### ISSUE THREAD

**Issue by GarySmith** [vmware-tanzu/octant#448]
In the fix for issue #204 , a few dash files were moved from internal to pkg so that they could more readily called from another app (thanks for that!). But alas, it is still not quite there. in pkg/dash/dash.go, Run requires being passed a logger object that must implement an interface (Logger) that is in an internal package, so there is no way to call this externally.

internal/commands/dash.go also has to jump through some hoops to create this logger based on a zap logger with some extra functions wrapped around this. Perhaps this logger and a simple constructor can be exposed into pkg/dash ?

**Comment by wwitzel3** [comment]
@GarySmith Ahh, ok, I think at a minimum we can move the log interface to pkg so that is can be implemented. I don't know if we want all of our logging code to move up in to pkg because then we will have people importing and depending on it and I think we want to keep the ability to be able to switch up and change our logging code on a whim.

**Comment by GarySmith** [comment]
Ok, that makes sense. Just need some ability to simply construct a logger and pass it along to Run, and keeping the details and implementation private is fine.

**Comment by aschiefe** [comment]
Circling back around to this after discussing plans with @dotNomad about how we're invoking octant.  Presently we are wrapping a command line style execution which, while @GarySmith was able to make it work, the end product presents a few issues that are less than ideal.  Out of curiosity has anything been done on improving the ability to embed octant since the last update of this issue?  Being able to embed octant without having to call command line redirects would most likely be a better solution for us long term.

**Comment by wwitzel3** [comment]
After discussing this during the 26th Feb 2020 community meeting, we determined that making a public logging interface that could be implemented so that the `Run` function could be called directly from tools that wish to embed Octant as their front end was something we can/will do and that we'd welcome PRs for this.

**Comment by dotNomad** [comment]
I'll take a stab at this!

**Comment by wwitzel3** [comment]
@dotNomad how are things going with this?

**Comment by dotNomad** [comment]
@wwitzel3 Really dove into this yesterday, and was struggling with some dependency caused import errors in airshipui. Working to solve that. I'll keep you updated with this as I continue.
