### ISSUE TITLE
Plugin: consider provide current kubecontext to plugins?

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#459]
The author of the Helm plugin would like to add a Delete action to the plugin.
https://github.com/bloodorangeio/octant-helm/issues/2

Currently the plugin author would have to reimplement the Helm delete code and then call our DashboardClient.Delete method.

If the plugin had access to the kubecontext, the plugin could directly call the Helm delete code, which creates its own client.

**Comment by bryanl** [comment]
I added the CRUD API as a safety net to stop rouge plugins from doing something insidious. If we expose the context, then plugins would be free to do more things, bit what is the impact on Octant? If we were to move forward with this, we'd need some sort of disclaimer that plugins can do anything they want with no safe guards. 

Now, in practice, what does this mean for plugin authors? More complexity when trying to use the API because we would deprecate/remove the existing functionality.  Also we would have to coordinate what the current context is. What does it mean for Octant? Not much. This would be a big change, so I'd like to see if anyone else has any input.

**Comment by wwitzel3** [comment]
Yep, we talked about that on slack. See https://kubernetes.slack.com/archives/CM37M9FCG/p1575483873227200?thread_ts=1575483873.227200&cid=CM37M9FCG

This issue is just to start a discussion around what a solution might be.

The solution maybe something to upstream Helm that decouples configuration of the client and the delete interface from the public delete call.

**Comment by wwitzel3** [comment]
A plugin can still easily do something insidious even without this feature. Nothing stops a plugin from fetching the kubeconfig from the filesystem once Octant starts it.

I do think that removing the need for plugins to have to think about if their calls to the API are going to the right place is a great reason to not expose the context directly.

I can't think of a way to expose the context that doesn't add a lot of complexity to plugin authors. I also think that if we expose the context folks might just default to using it directly which I think would a bad direction for plugins to go.

**Comment by jdolitsky** [comment]
> A plugin can still easily do something insidious even without this feature. Nothing stops a plugin from fetching the kubeconfig from the filesystem once Octant starts it.

FYI - this is a workaround that I started to legitimately consider because I do not have access to the context. It's obviously not the ideal direction... I'll play around with this some more and report back.

I suppose this is a non-issue for CRDs, since the controller would take the responsibility of cleaning up the necessary things on delete.

**Comment by wwitzel3** [comment]
@jdolitsky So we definately don't want to provide the entire kubeconfig.

Would exposing a `Context()` method and an `ContextChanged()` callback be sufficient? The first would allow you fetch the current active context and the second would be a callback that Octant sent the current context to if the user changes it.

**Comment by jdolitsky** [comment]
@wwitzel3 this would be helpful in order to filter out releases by namespace, but it actually would not solve the issue. Helm vendors in client-go and calls NewForConfig: 

https://github.com/helm/helm/blob/6cc039ea79a435c9f335d677b78d9be574b8e770/pkg/action/action.go#L144
https://github.com/kubernetes/client-go/blob/master/kubernetes/clientset.go#L370

**Comment by wwitzel3** [comment]
What would we need to add so that the plugin could successfully implement KubeClient interface by wrapping the plugin API?

One thing I see, is exposing the Kube and API versions and making the `getCapabilities` internal method overridable. Right now it is called internally by the uninstall action.

I think we could craft a KubeClient and a suitable Capabilities struct by extending the Plugin API to provide some of the data needed.

**Comment by wwitzel3** [comment]
Resolved. The plugin API now support all verbs but `Watch`
