### ISSUE TITLE
In overview summary generate conditions table if conditions are detected

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#566]
In the overview summary, we have hardcoded conditions tables for certain GVKs. We can simplify this by automatically adding conditions if we detect `.status.conditions`. The win is that any object (including CRDs) that has conditions would automatically get this table.

**Comment by wwitzel3** [comment]
Just to help with scoping on this issue, I know there has been some desire to change the display of conditions as well. I want to focus on first getting the auto detection working, as a table. We can open a new issue around improving the UX of these conditions after we have them displaying automatically.

**Comment by wwitzel3** [comment]
This will enable #489 to be completed fairly easily.

**Comment by GuessWhoSamFoo** [comment]
The way to approach this problem is similar to how events are handled. See https://github.com/vmware-tanzu/octant/blob/master/internal/printer/object.go#L59

Instead of having to set conditions for each type in `printer`, it'd be a toggle or something enabled by default. An example of this is in https://github.com/vmware-tanzu/octant/blob/master/internal/printer/pod.go#L124
