### ISSUE TITLE
crash when viewing workloads

### ISSUE THREAD

**Issue by maehld** [vmware-tanzu/octant#568]
Hi. Octant 0.10 crashes when I click on Workloads. Everything else seems to function normally.

The error is:

`goroutine 585 [running]:
github.com/vmware-tanzu/octant/internal/api.notFoundRedirectPath(0xc000084bc0, 0x1b, 0x25, 0x0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/stream.go:39 +0x170
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent(0xc0001ce800, 0x25eadc0, 0xc000222680, 0x26174a0, 0xc0000deb00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:136 +0x3f4
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1(0x25eadc0, 0xc000222680, 0x0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:98 +0x109
github.com/vmware-tanzu/octant/internal/api.(*job).run.func1(0xc00041ea20, 0xc0001780e0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:111 +0x43
created by github.com/vmware-tanzu/octant/internal/api.(*job).run
        /go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:110 +0x95
`

I tried it with an older cluster of ours and a newly installed minikube on Windows. I found a similar error message in #549 but I haven't even enabled a metrics server in minikube.

**Comment by wwitzel3** [comment]
@maehld Thank you for reporting this. I'm going to get minikube on Windows and see if I can replicate this behavior.

**Comment by wwitzel3** [comment]
Found the issue, our `notFoundRedirectPath` helper makes some assumptions about the length of the request path. Which is causing `panic: runtime error: slice bounds out of range [:-1]`

**Comment by wwitzel3** [comment]
Taking that further, it looks like the Workloads path on windows is being escaped. `http://127.0.0.1:7777/#/workloads%5Cnamespace%5Cdefault` which is why the redirect is failing.

That said, I will apply two fixes here. I will ensure the path is rendering correctly, but I will also make sure that if the length of the path parts does not calculate to at least 1 in size, we just default to logging an invalid path error and redirecting to the root.
