### ISSUE TITLE
Ability to restrict to a handful of namespaces

### ISSUE THREAD

**Issue by Stono** [vmware-tanzu/octant#582]
Firstly; absolutely great tool - I am very impressed.

As for a feature request; i'd love to be able to deploy this to our cluster and at deploy time configure (maybe with a label selector) which namespaces octant will access.  We want to deploy it on our cluster because we have 250+ devs, so distributing tooling across the org like that is hard.

For context here, we have 330 services deployed in 330 namespaces, and they're owned by approximately 20 squads.

I'd love to give each squad their own instance of this, which only has access to their namespaces.

**Comment by wwitzel3** [comment]
Hi @Stono 

Octant is a desktop application, despite its current packaging and using a web browser as the UI client. Having any type of startup filter/selector to limit namespaces would merely create a facade of access control. Octant will have the same access as the kubeconfig that is used to start it.

With that said, what you want to do is achieved very easily without having to install anything in a cluster at all. Octant is a stand-alone binary and doesn't require any privileged access to the system and it will use the local kubeconfig. So your developers can use what ever mechanism they already use to install tooling, like `brew` or `chocolatey` or direct download.

When they start Octant they would only have access to the namespaces their local kubeconfig allows and since Octant allows you to easily switch contexts once it is running, they would be able to switch between them.

If you want some mechanism to distribute kubeconfig files you can do that via 1Password or LastPass or other tool for storing and sharing sensitive information.

**Comment by Stono** [comment]
Yeah I figured that might be the answer, unfortunately distributing gcloud, kubectl, and octant across our organisation in a consistent manner and then further managing their kube credentials is currently a no go for us.   

We’ve done extremely well by centralising our common tooling deployed onto the cluster and protected by RBAC both from a login and clusterrole perspective. 

I appreciate however that it isn’t the direction of travel for this tool so I will find an alternative :)

Thank you for your prompt response.
