### ISSUE TITLE
Move Terminal component to tab

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#664]
Currently the terminal component is created by executing a command using a button on the container in the pod listing.

Move the terminal window to its own tab. defaulting the command to be executed to /bin/sh and having a drop down to select which container the terminal is open against.

This to consider when implementing this:
 - what is /bin/sh is not found?
    - currently users specify the command they want to run, is this going away?
 - how long does the terminal stay open after navigating away without explicitly exiting?
 - if a user explicitly exits a terminal, does clicking away and back to the tab restart the session?
 - does navigating away from the tab exit the terminal session?
     - if exiting does end the session automatically, should we save session scrollback for later retrieval?

**Comment by rossfenrick** [comment]
I'll have to think about this some more but another option would be moving the command to the view heading next to the delete button:
![Screen Shot 2020-02-12 at 11 26 02 AM](https://user-images.githubusercontent.com/7506366/74369689-a6f32680-4d8a-11ea-9ee1-72c1c0760e38.png)

**Comment by gandazgul** [comment]
This would be awesome!

**Comment by mklanjsek** [comment]
My initial thought was that `Terminal` should not be in top right corner where we only have immediate actions, like `Delete`, etc.  But to @rossfenrick point, it is an action after all so that may be a right place for it.

As fo other questions, I think we should start with the reasonable defaults and add things like command to run to global settings.

@wwitzel3 thoughts?

**Comment by wwitzel3** [comment]
- There will be a Terminal tab.
- The default command will be `/bin/sh` - w
- When you click on the tab, if no session exists, a new terminal session will be created.
- The session will remain active as long as you remain on the pod.
- When you navigate away from the pod, the session will be closed.
- If you exit an active session `# exit` the backlog will remain until you reconnect OR navigate away from the pod.

**Comment by wwitzel3** [comment]
The changes above also mean:

- No longer a need for  a terminals listing describer

**Comment by GuessWhoSamFoo** [comment]
Paired with @mklanjsek a bit on this today.

 - Since there is only one tab per pod, terminal manager should support a key value store of pod names and terminal ID per namespace.
 - We tried to handle creating terminal instance only on the backend. This will not work because backend does not track active tab.
