### ISSUE TITLE
All workloads should have a combined log viewer that contains descendant pods logs.

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#668]
Workloads should have a `Logs` tab which shows a combined view of all descendant pod logs. The existing log viewer would need to be updated to show the pod which created the log.

**Comment by mklanjsek** [comment]
K8s logs collection is done on pod level, so we need to aggregate logs from multiple pods.  It looks like it would be possible to do that on client side by starting multiple streams (one for each pod) in `PodLogsService` but it would probably be a better idea to do that on the server side.  I am inclined towards former because on a long run it can give us more metadata about each log entry and better filtering capabilities.
@vmware-tanzu/octant-owners any thoughts?
