### ISSUE TITLE
How to install in Alpine.

### ISSUE THREAD

**Issue by luismanuelmontoro** [vmware-tanzu/octant#682]
Exist any image in dockerhub for install octant? can i install in Alpine linux?

**Comment by wwitzel3** [comment]
Octant is an application that runs on Windows, macOS, and Linux. We do not distribute via Dockerhub or provide a Docker image for Octant because the methods for running a desktop applicaton inside a docker container vary so much depending on the Docker host.

We recommend you download and execute the binary directly from our releases page on GitHub.

That said, to get Octant running with Docker, currently you'll need an image with a browser and Octant installed, but once we have moved fully to an Electron app you shouldn't need to worry about the browser.

Here are some blog posts that might help:
- https://blog.jessfraz.com/post/docker-containers-on-the-desktop/
- http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
