### ISSUE TITLE
Selectors do not display correctly when there is no room

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#906]
**What steps did you take and what happened:**

Selectors are cut off when there is no room left.

<img width="1658" alt="Screen Shot 2020-05-02 at 1 41 50 PM" src="https://user-images.githubusercontent.com/240/80871473-d83d0d80-8c7a-11ea-83fc-9f0326b37fa2.png">

**What did you expect to happen:**

They should act the same way as labels.

**Comment by mklanjsek** [comment]
This should be mitigated after work on label/selector tooltips covered in #903 is merged. The intent of Tooltips is to give easy access to complete text in situations with limited space.  

However, the positioning algorithm should be more aggressive, and when column is so narrow we should only show one label and badge instead of two. I'll add that functionality as part of #903.

**Comment by mklanjsek** [comment]
Fixed by #903
